### ISSUE TITLE
PR to sphinx?

### ISSUE THREAD

**Issue by nlgranger** [hagenw/sphinxcontrib-katex#1]
Are there any plans for submitting this work as an official extension to sphinx?
(thanks for this project btw)

**Comment by hagenw** [comment]
There was a discussion on KaTeX and sphinx some time ago and the outcome was that sphinx has already maintenance problems and will not include new math extensions: https://github.com/sphinx-doc/sphinx/issues/2430

Considering that discussion, I guess sphinxcontrib-katex will continue as an external extension.

Note, that there are also some issues with the current CSS implementation, e.g. https://github.com/rtfd/sphinx_rtd_theme/pull/383#issuecomment-355825628. I will try to enhance this during the next weeks and add more documentation.

**Comment by nlgranger** [comment]
Ok, thank you for the details.
