### ISSUE TITLE
Option to pre-render?

### ISSUE THREAD

**Issue by ezyang** [hagenw/sphinxcontrib-katex#11]
According to the KaTeX documentation, it supports prerendering HTML server side so that no JS has to run on client. Is this supported by sphinxcontrib-katex? If it is not, do you have any idea how difficult it would be to add support?

**Comment by hagenw** [comment]
Hi, thanks for the suggestion.
So far it is not supported. For me as a non-expert regarding Node.js, the documentation provided by KaTeX was not sufficient to consider it.

Are you able to create a pull request for it?

**Comment by ezyang** [comment]
I'd have to look into it. What I expect to happen is that we invoke KaTeX via nodejs, it gives a bunch of html, and then we need to dump it into the Sphinx generated HTML. So, shouldn't be too bad, if this extension is setup to inject raw html (which it should be?)

**Comment by hagenw** [comment]
yes, it injects HTML, compare https://github.com/hagenw/sphinxcontrib-katex/blob/ba0db20a7a15be1eb975d642d121d3faa867b8ae/sphinxcontrib/katex.py#L77-L102

**Comment by ezyang** [comment]
This ended up being pretty easy. I'll post a shitty version of the patch (that breaks some existing functionality and is not configurable) and maybe we can talk about how to support the other bits correctly.

**Comment by hagenw** [comment]
KaTeX server side pre-rendering is included with sphinxcontrib-katex 0.5.0.
