### ISSUE TITLE
offline css and fonts

### ISSUE THREAD

**Issue by kalvdans** [hagenw/sphinxcontrib-katex#122]
I found out that even with `katex_prerender=True` the generated documentation wants to fetch `katex.min.css` from the Internet. I've solved it by installing `libjs-katex` Ubuntu package and added the following to my `conf.py`:
```
html_static_path = ["/usr/share/javascript/katex"]
katex_prerender = True
katex_css_path = "katex.min.css"
```

The problem is now that the css comes from a different katex version than what was used to render the HTML. I seek advice here how we should solve the problem:

1. Bundle all katex static resources into sphinxcontrib-katex,
2. Make the `katex.min.js` path configurable in `katex-server.js` so I can point it to `/usr/share/javascript/katex/katex.js`, or
3. Don't do anything and leave it to the user to make sure katex_css_path points to the same version as bundled with sphinxcontrib-katex.

**Comment by hagenw** [comment]
The default behavior at the moment is to fetch `katex_css_path` from the Internet, see https://sphinxcontrib-katex.readthedocs.io/en/v0.9.9/configuration.html

The KaTeX version set in the config is always set to match the one of the `katex-server.js` file, which is bundled with the extension to build the package. So there should not be any version mismatch with the default settings.

But I'm also open to changes, e.g. I can't remember why I decided to not bundle the CSS file with the extension together, whereas for the other files it seems to be the case.

**Comment by hagenw** [comment]
Sorry, I misinterpreted

https://github.com/hagenw/sphinxcontrib-katex/blob/296c71e6a41e97513716e9512e163574d393b466/sphinxcontrib/katex.py#L374-L388

You need to install indeed `katex` on your system for pre-rendering:

https://github.com/hagenw/sphinxcontrib-katex/blob/296c71e6a41e97513716e9512e163574d393b466/.github/workflows/katex.yml#L35-L37

So it is possible to get a non-matching `katex` version.

This will then also not be solved by

> 1. Bundle all katex static resources into sphinxcontrib-katex

as we will not bundle the `katex` executable in the extension.

As `katex_js_path` let's you configure the path to `katex.min.js`, `katex-server.js` should maybe be fixed to respect the selected value. But I'm not sure if this could break the server if a version is selected, that is not compatible with the `katex-server.js` file.

**Comment by kalvdans** [comment]
> You need to install indeed `katex` on your system for pre-rendering:

I think this is a documentation bug. Only `nodejs` is needed on the system, and then the bundled `katex.min.js` is used for pre-rendering. There's nowhere a `katex` executable is run.

**Comment by hagenw** [comment]
Thanks for pointing this out. I removed the `katex` installation from the corresponding test in #124.

And we can also pass on the path to `katex.min.js` to `katex-server.js` as proposed by your second solution, as it is set already at

https://github.com/hagenw/sphinxcontrib-katex/blob/77aab650a16fc3fdd384788cf077f81380be3aa9/sphinxcontrib/katex.py#L385-L386

The only think missing is that this respects the `katex_js_path` config entry. I will try to update this tomorrow.

**Comment by kalvdans** [comment]
Thanks yourself @hagenw for swift response and action! I can try out a pull request if you make one for `katex_js_path`.

**Comment by hagenw** [comment]
I have now released version 0.9.10, including the changes from https://github.com/hagenw/sphinxcontrib-katex/pull/128

**Comment by kalvdans** [comment]
Great!

@hagenw , you wanted to keep the bug open for some thoughts in https://github.com/hagenw/sphinxcontrib-katex/pull/128#issuecomment-2095887089 , can you explain it in more detail here?

**Comment by hagenw** [comment]
Yes, at the moment `katex.min.css` is requested from the Internet, and you cannot set it to a local file.
The question is if we should include it in the package as well and allow for both using the included version, any path, or a path on the internet as at the moment.

BTW, for `katex.min.js` we do not support a path on the internet at the moment.

**Comment by kalvdans** [comment]
> Yes, at the moment `katex.min.css` is requested from the Internet, and you cannot set it to a local file.

You can set it to a local file, and that's what I did with the following lines:
```
html_static_path = ["/usr/share/javascript/katex"]
katex_css_path = "katex.min.css"
```

It inserts these html tags in the resulting documentation:
```
      <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
      <link rel="stylesheet" href="_static/katex.min.css" type="text/css" />
      <link rel="stylesheet" href="_static/katex-math.css" type="text/css" />
```

**Comment by hagenw** [comment]
Great, that's better than I had expected.

Then the only remaining question is if we should include the CSS file as well with the extension instead of loading it from an external URL. I would vote for staying with the current solution as providing the CSS file via CDN [has advanatges of a local file on the server](https://webmasters.stackexchange.com/a/92182).

Nonetheless, we could think about adding `katex.min.css` to the extension, and mentioning in the documentation, that the user can switch to the local CSS file by setting `katex_css_path = "katex.min.css"`.

**Comment by kalvdans** [comment]
> I would vote for staying with the current solution as providing the CSS file via CDN has advantages

me too

> Nonetheless, we could think about adding katex.min.css to the extension

Then we need to bundle the fonts as well, a total of 2.3 MB data. I'll let you decide.

**Comment by hagenw** [comment]
OK, as the current package is around 96K, I would vote against bundling the CSS file and fonts with it.

I will close this issue for now.
