### ISSUE TITLE
How to integrate katex in sphinx and render correctly in offline mode without network

### ISSUE THREAD

**Issue by phoenixsfly** [hagenw/sphinxcontrib-katex#131]
I want to build static documents with sphinx and view them offline, but by default the katex js script is loaded via CDN.
I tried downloading the katex script and putting it in the `_static` directory, but that didn't work.
sphinx-mathjax provides an offline run option: this can be solved by installing `sphinx-mathjax-offline`  extension. Can `sphinxcontrib-katex` achieve a similar effect?

**Comment by hagenw** [comment]
You can set the config variable `katex_css_path` to load a local CSS file instead from CDN.

If you want to use the KaTeX JS server bundled with the extension, or a custom one from a local path (compare https://github.com/hagenw/sphinxcontrib-katex/pull/128), you need to use the pre-render mode by using the `katex_prerender = False` configuration.

**Comment by phoenixsfly** [comment]
> You can set the config variable `katex_css_path` to load a local CSS file instead from CDN.
> 
> If you want to use the KaTeX JS server bundled with the extension, or a custom one from a local path (compare #128), you need to use the pre-render mode by using the `katex_prerender = False` configuration.

Thanks for the reply， I  set `katex_css_path` and **copied `katex/font` folder to `_static` directory**, and then the latex formula was rendered. 
However, there was another problem with the rendering format, and I will open a separate issue to describe it
