### ISSUE TITLE
No render equations with nbsphinx

### ISSUE THREAD

**Issue by carlosal1015** [hagenw/sphinxcontrib-katex#28]
Hello, it is good to know that [MathJax is disabled by default in Sphinx](https://github.com/sphinx-doc/sphinx/issues/5568). My issue report is the following:

I installed in two python 3.8.2 environment the packages `sphinx==2.4.4`, `sphinxcontrib-katex==0.6.0` and `nbsphinx==0.5.1`, indeed, the last versions of each one.

I did an experiment and isolated two Sphinx projects called 1 and 2 with the packages mentioned above, the only difference between these is `conf.py`.
![DeepinScreenshot_select-area_20200316112602](https://user-images.githubusercontent.com/21283014/76779099-cfe74c80-6778-11ea-99ed-9fb602d45ad0.png)
![DeepinScreenshot_select-area_20200316112634](https://user-images.githubusercontent.com/21283014/76779104-d249a680-6778-11ea-853e-d30fb97a9b5e.png)
i.e, 1 load `sphinxcontrib-katex` and 2 load `sphinxcontrib-katex` and `nbsphinx`. Then, when I build both projects and put some math in the front page:
![DeepinScreenshot_select-area_20200316114439](https://user-images.githubusercontent.com/21283014/76780553-438a5900-677b-11ea-97d0-68c949db17d2.png)
Whose sources HTML generated by Sphinx are
![DeepinScreenshot_select-area_20200316121745](https://user-images.githubusercontent.com/21283014/76783453-de853200-677f-11ea-901f-ea7c81a9c4e4.png)
Hence, there are similar, the difference match on line 17 on 2.
![DeepinScreenshot_select-area_20200316110719](https://user-images.githubusercontent.com/21283014/76777308-02dc1100-6776-11ea-88f2-3f767a402bd8.png)
And render the math (if I comment the line 17 in `index.html` from 2):
![DeepinScreenshot_select-area_20200316110801](https://user-images.githubusercontent.com/21283014/76777392-2010df80-6776-11ea-94fc-26cc0c7032cb.png)
![DeepinScreenshot_select-area_20200316114124](https://user-images.githubusercontent.com/21283014/76780550-41c09580-677b-11ea-95ec-dded6d71023d.png)

Please, could you review this behavior? Maybe the issue will be on [`nbsphinx`](https://pypi.org/project/nbsphinx/) and not in [`sphinxcontrib-katex`](https://pypi.org/project/sphinxcontrib-katex/).

Thank you.

**Comment by carlosal1015** [comment]
Hello, in the docs of nbsphinx it is possible to disable `requirejs`. This solved the [issue](https://github.com/spatialaudio/nbsphinx/issues/409#issuecomment-599997252) too. Here, he suggest to  work KaTeX with RequireJS.

**Comment by hagenw** [comment]
Cool, thanks for reporting this. I will check if there is a way around this, so you don't need an extra option to disable `requirejs`.

BTW, I also use `nbsphinx` quite a lot, but never had this issue before. Does the order in the `config.py` of including the extensions makes a difference?

```python
extensions = [
    'nbsphinx',
    'sphinxcontrib.katex',
]
```
versus
```python
extensions = [
    'sphinxcontrib.katex',
    'nbsphinx',
]
```

**Comment by carlosal1015** [comment]
Hi @hagenw, I swap the extensions without `nbsphinx_requirejs_path = ''` in the `conf.py`.

I reported the errors from console [here](https://github.com/spatialaudio/nbsphinx/issues/409#issuecomment-600281587) if may help.

Thanks.

**Comment by mgeier** [comment]
This has been fixed in https://github.com/spatialaudio/nbsphinx/pull/412, which is part of the latest (0.6.0) release of `nbsphinx`.

With that, the order of extensions doesn't matter anymore, it should just work out-of-the-box.

**Comment by hagenw** [comment]
Cool, thanks for fixing this.
