### ISSUE TITLE
Gitlab math markdown rendered in sphinx

### ISSUE THREAD

**Issue by mlisovyi** [hagenw/sphinxcontrib-katex#32]
I bumped into this project as gitlab mentions that they use KaTeX to render math in markdown. And it looks very promising for what i have in mind.

However, i bump into the problem, that gitlab uses dollar_sign+backtick for inline math rendering (https://docs.gitlab.com/ee/user/markdown.html#math). The issue is that even if i configure 
```python
katex_inline = ['$`', '`$']
```
When i generate sphinx html from markdown I still get formula from rendered as $code_block$. As if markdown translation kicks in before   `sphinxcontrib.katex` and there is no expected pattern left for KaTeX to render.

Do you have a hint on how one can overcome it? Thanks in advance

**Comment by hagenw** [comment]
Mh, good question. 

Have you tried to escape the backtics:

```python
katex_inline = [r'$\`', r'\`$']
```

**Comment by mlisovyi** [comment]
Nope, sadly it doesn't help. I tried many possible combos (but most likely not all :) ), but i now double-checked that it doesn't solve the problem

**Comment by hagenw** [comment]
How is markdown handled at all by sphinx, do you have to use `recommonmark` as mentioned here https://www.sphinx-doc.org/en/master/usage/markdown.html?

There they say they expect the following for [inline math](https://recommonmark.readthedocs.io/en/latest/auto_structify.html#inline-math):

```
This formula `$ y=\sum_{i=1}^n g(x_i) $`
```
which looks different from what Gitlab is doing.

**Comment by mlisovyi** [comment]
Yes, correct. We are using `recommonmark` to convert Markdown. And yes, the math notation in CommonMark is different from gitlab. The challenge is that we want to have docs in both :)
We have fixed math notation by gitlab and I was thinking of `sphinxcontrib-katex`, because it allows to provide a custom math separator as configuration.
But ok, it seems i will need to implement a workaround and re-format our markdown dynamically using custom code in `conf.py`, unless you see a more elegant way. Maybe there is a way to execute `sphinxcontrib-katex` before `recommonmark`?

**Comment by hagenw** [comment]
I don't know how exactly `recommonmark` works, but you might try to put `sphinxcontrib-katex` in front of it in the list of extensions, e.g.:
```python
extensions = [
    'sphinxcontrib-katex',
    'recommonmark',
]
```

If this doesn't work, I'm afraid you have to look into the code how `recommonmark` handle the parsing there.

**Comment by mlisovyi** [comment]
this unfortunately doesn't work either. Thanks for help. I'm closing this issue, as there is no obvious solution
