### ISSUE TITLE
Speed up pre-rendering?

### ISSUE THREAD

**Issue by CalebBell** [hagenw/sphinxcontrib-katex#37]
Hi Dr. Wierstorf,

Thank you very much for your creation of this package! It is incredibly useful and speeds up page loads a ton.

I was recently looking to speed up page loads even more (I use a lot of equations in my [documentation](https://fluids.readthedocs.io/fluids.geometry.html#fluids.geometry.V_horiz_torispherical). I found the pre-rendering option of your project, and was able to use it locally quite successfully. The savings in load time is 30-40% for many pages; the original speed improvement from using katex in the first places was 200-400%.

When I went to use that option with readthedocs however, it turns out they have a 15-minute time limit and the servers aren't quite as a fast as even a slow laptop. Because of the number of equations I use, the build time went from 300 s to 2200 s; over their time limit. They suggested the performance of the extension might be the issue, so I took a look and wanted to share my findings.

I believe the slowdown comes because a new katex process is started for every single equation. Their is a lot of overhead to loading a new node process and having it read and run katex. I looked around to see if there were other Python projects calling katex, and I was able to find [one](https://github.com/cqql/pelican-katex). The approach it takes is to start up a node process, which runs some custom [javascript](https://github.com/cqql/pelican-katex/blob/master/pelican_katex/render-katex.js), and operates as a server to process requests. 

I was able to macgyver sphinxcontrib-katex into using the same approach with their code and using their [Python wrapper](https://github.com/cqql/pelican-katex/blob/master/pelican_katex/rendering.py). The timing table with the new approach is as follows:

68.5 - no pre-rendering
346.8 s - pre-rendering with currently included approach
77.3 - pre-rendering with server approach

I understand that this approach is substantially more complicated than the current implementation. It is also based around GPL licensed code. I am not an expert in javascript either, and I would have a hard time debugging issues with the javacsript wrapper. I don't think I can offer a pull request with this implemented, and for now it looks like the solution I can afford is to just turn prerendering off.

I though I would share my experience for any future people who ran into this issue.

Have a happy new year and thanks again for this project!

**Comment by hagenw** [comment]
Cool, thanks for debugging this issue.
So far I haven't used the pre-render option in my personal projects. It was mainly requested by https://pytorch.org/docs, but I plan to use it in the near future and will see if I can update the code.

**Comment by shivshankardayal** [comment]
This is very much needed. My build times are in excess of 15 min for one project.

**Comment by shivshankardayal** [comment]
Also, can we use multiple processes to process the documents, please?

**Comment by hagenw** [comment]
I had a brief look into the problem, but so far I haven't found an easy implementation for speeding up pre-rendering.
So, I'm afraid this will have to wait or we find somebody willing to work on it.

**Comment by shivshankardayal** [comment]
It seems I will have to get my hands dirty. :P Let me go through this extensions code and perhaps I can pull up something.

**Comment by shivshankardayal** [comment]
It seems that I was able to integrate pelican solution to this extension. It includes adding two JS files and adding some code from pelican latex. Since that lib is GPL will it be possible to add that here? My build time has reduced from 5 min to 3 seconds.

**Comment by shivshankardayal** [comment]
If license is an issue I can reimplement what pelican-katex has done to circumvent this problem. However, I do not know how to copy the Javascript files to build directory.

**Comment by hagenw** [comment]
Cool, that you managed to find already a solution. GPL code is indeed a problem as we cannot include it in a MIT licensed project without changing the license to GPL as well. So, I'm afraid we need to re-implement the needed code.

> However, I do not know how to copy the Javascript files to build directory.

This question I do not understand.

Maybe, you just start creating a pull request and we can continue discussing open questions there?

**Comment by shivshankardayal** [comment]
Let me reimplement the pelican katex implentation and I will create the PR. I figured out how to copy js files to installation directory.

**Comment by hagenw** [comment]
Server side pre-rendering was implemented in https://github.com/hagenw/sphinxcontrib-katex/pull/69
