### ISSUE TITLE
Error with Sphinx 4.0.0b1

### ISSUE THREAD

**Issue by SeanDS** [hagenw/sphinxcontrib-katex#38]
Looks like the removal of `add_stylesheet` in Sphinx 4.0.0 has broken this extension. I get this error when building a project with Sphinx 4.0.0 and this extension:

```
Extension error (sphinxcontrib.katex):
Handler <function builder_inited at 0x7fa28fa17700> for event 'builder-inited' threw an exception (exception: 'Sphinx' object has no attribute 'add_stylesheet')
```

I believe the problem is probably [this line](https://github.com/hagenw/sphinxcontrib-katex/blob/a99711b1603aff83682787ef13aa6ae445410d9e/sphinxcontrib/katex.py#L1400):

```python
    add_css = getattr(app, 'add_css_file', getattr(app, 'add_stylesheet'))
```

This doesn't work if `add_stylesheet` doesn't exist as an attribute of `app`, which is the case from Sphinx 4.0.0.

**Comment by hagenw** [comment]
Thanks for reporting.
As a first step I released version 0.7.2 of `sphinxcontrib-katex` which depends now on `sphinx<4.0.0`.
In a next step the `add_stylesheet` problem needs to be fixed.
