### ISSUE TITLE
Compatibility with Sphinx 4.0?

### ISSUE THREAD

**Issue by davidfritzsche** [hagenw/sphinxcontrib-katex#63]
Thanks for this great project.

I was wondering about the status with respect to Sphinx 4.0.

In the `setup.cfg` the dependency on sphinx is listed as strictly `< 4.0.0`: https://github.com/hagenw/sphinxcontrib-katex/blob/c6456022c32c540ffc5db6c684d8f8bf70a966f3/setup.cfg#L32

The changelog entry for version 0.8.0 (https://github.com/hagenw/sphinxcontrib-katex/blob/master/CHANGELOG.rst#version-080-2021-05-18) lists support for Sphinx >= 4.0.

**Comment by hagenw** [comment]
Should be fixed in version 0.8.6 of `sphinxcontrib-katex`. Thanks for reporting.
