### ISSUE TITLE
Configuration error with Sphinx 5.0.0 or later

### ISSUE THREAD

**Issue by carlosal1015** [hagenw/sphinxcontrib-katex#70]
Hi, thanks for the nice package. The following behavior starts when [`python-sphinx upgrade to 5.0.0-1`](https://archlinux.org/packages/community/any/python-sphinx).

When we run this lines
```console
$ python -m sphinx docs docs/_build/ -c docs/ -b html -W
$ python -m sphinx docs docs/_build/ -c docs/ -b latex -W
```
we see
```
==> Starting check()...
Running Sphinx v5.0.0
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/tmp/makepkg/python-sphinxcontrib-katex/src/sphinxcontrib-katex-0.8.6/docs/conf.py", line 5, in <module>
    import sphinxcontrib.katex as katex
ModuleNotFoundError: No module named 'sphinxcontrib.katex'
==> ERROR: A failure occurred in check().
```

OS: Arch Linux.
Package: [`python-sphinxcontrib-katex 0.8.6`](https://aur.archlinux.org/packages/python-sphinxcontrib-katex)

**Comment by hagenw** [comment]
https://github.com/mcmtroffaes/sphinxcontrib-bibtexuses the same naming strategy, so we could maybe look there for a solution, or check if we get the same error for that package.

**Comment by carlosal1015** [comment]
Thank, I will invest more reproducing more, my setup is Arch Linux but I will try to look more deeper what is happening.

> @carlosal1015 which Python version did you use?
> 
> I used Python 3.8 and tried to reproduce your error by compiling the documentation of this project with `sphinx==5.0.0` and `sphinx==5.0.1` and in both cases it worked without any error.

From here, [python 3.10.4-2](https://github.com/archlinux/svntogit-packages/blob/packages/python/trunk/PKGBUILD) 

This is my full log with Arch Linux setup. For brevity I only pasted the error zone.

https://gitlab.com/carlosal1015/aur/-/jobs/2542770481

**Comment by carlosal1015** [comment]
> [mcmtroffaes/sphinxcontrib-bibtex](https://github.com/mcmtroffaes/sphinxcontrib-bibtex) uses the same naming strategy, so we could maybe look there for a solution, or check if we get the same error for that package.

We got a lot of errors, but none (I guess) related with the exactly same error.
Version:

- [`python-sphinxcontrib-bibtex 2.4.2-1`](https://archlinux.org/packages/community/any/python-sphinxcontrib-bibtex)
- [Video](https://asciinema.org/a/499329)
- [Raw log](https://github.com/hagenw/sphinxcontrib-katex/files/8833436/log.txt)

**Comment by hagenw** [comment]
Thanks, in the meantime I figured out a solution along the lines of https://github.com/mcmtroffaes/sphinxcontrib-bibtex/commit/65153f78ae9c7248dc31de6597acf062f6c11aab, but I did not yet manage to make it work also for Python 3.6.

**Comment by carlosal1015** [comment]
Thank you very much, [is fixed now](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-sphinxcontrib-katex&id=10d12867ccc5edc369a0086a37a60c1ac1cca4d7) and [tested](https://gitlab.com/carlosal1015/aur/-/jobs/2575451191).
