### ISSUE TITLE
Add a script for updating the KaTeX version

### ISSUE THREAD

**Issue by hagenw** [hagenw/sphinxcontrib-katex#79]
Every time we want to update to a new KaTeX version we need to change the version at a few places, namely

https://github.com/hagenw/sphinxcontrib-katex/blob/e643524b34edddb30517f77eadea2d5c614b9957/sphinxcontrib/katex.py#L28

https://github.com/hagenw/sphinxcontrib-katex/blame/e643524b34edddb30517f77eadea2d5c614b9957/README.rst#L85-L89

and after merging https://github.com/hagenw/sphinxcontrib-katex/pull/69 we also need to download a new version of `sphinxcontrib/katex.js` from https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.js

It would be nice, if we can automate all of this by just calling a script and providing the version number as argument.

**Comment by carlosal1015** [comment]
Hi @hagenw, maybe someone of three options helps you

#### with curl

Based in [this suggestion](https://aur.archlinux.org/packages/visual-studio-code-bin#comment-868805) and the use of [jq](https://stackoverflow.com/a/39231150/9302545), [markdown guides](https://github.com/tldr-pages/tldr/blob/main/pages/common/jq.md).

```console
$ curl 'https://registry.npmjs.org/katex' | jq '.["dist-tags"]["latest"]'
```

#### using a web notification

for example [newreleases.io](https://newreleases.io)

![image](https://user-images.githubusercontent.com/21283014/173102466-b35ae92d-d392-4f82-bb95-1189e0cb4762.png)
![image](https://user-images.githubusercontent.com/21283014/173102560-58be8049-cc14-47b6-9f82-51dcd46e0e26.png)

### cli with github action

[`nvchecker`](https://nvchecker.readthedocs.io/en/latest/usage.html#check-npm-registry) can check new versions of some piece of software. only required a file called `config_file.toml`

```toml
[__config__]
oldver = "old.txt"
newver = "new.txt"

[katex-npm]
source = "katex"
npm = "katex"
```

[Github action](https://github.com/sunlei/nvchecker)
